services:
  maftourbot-db:
    image: postgres:16
    environment:
      POSTGRES_DB: maftourbot
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - overlay-postgres-data:/var/lib/postgresql/data
    networks:
      - overlay
    healthcheck: # Add health check for better service readiness tracking
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      retries: 5
      timeout: 5s

  maftourbot:
    image: ghcr.io/vyasma-mafia/maftourbot:master
    #    build: .
    container_name: maftourbot
    ports:
      - "8090:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://maftourbot-db:5432/maftourbot
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - .env
    depends_on:
      overlay-db:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: service
    labels:
      service: "maftourbot"
    networks:
      - maftourbot

volumes:
  maftourbot-postgres-data:

networks:
  maftourbot:
